[tool.poetry]
name = "nom_du_projet"
version = "0.1.0"
description = "Description du projet"
authors = ["Votre Nom <votre@email.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
